name: Unit Tests

on:
  push:
    branches:
      - main
      - develop
  pull_request:

jobs:
  golangci:
    name: Run unit tests
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: stable

      - name: Install dependencies
        run: go mod download

      - name: Run tests
        run: go test -v ./...
